name: Update Repository and Create Pull Request

on:
  workflow_call:
    inputs:
      input-zip:
        required: true
        type: string
      relative-path:
        required: true
        type: string
        default: "."

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Downloads this repo when called outside
      - name: Checkout reusable workflow dir
        uses: actions/checkout@v3
        with:
          repository: datafund/auto-code-update
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          path: auto-code-update

      # Step 2: Download the zip file from the predefined URL
      - name: Download zip file
        run: |
          curl -L -o downloaded.zip "${{ inputs.input-zip }}"

      # Step 3: Extract the zip file
      - name: Extract zip file
        run: |
          unzip downloaded.zip -d extracted/

      # Step 4: Run Python script to modify the repository
      - name: Run Python script
        run: |
          python3 ${GITHUB_WORKSPACE}/auto-code-update/src/merge.py extracted/ "${{ inputs.relative-path }}"
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      # Step 6: Cleaning unused files
      - name: Clean
        run: |
          rm -r extracted/ && rm downloaded.zip

      # Step 6: Commit changes
      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Automated update by GitHub Action" || echo "No changes to commit"

      # Step 7: Push changes to a new branch
      - name: Push changes
        id: push-changes
        run: |
          BRANCH_NAME="update-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

      # Step 8: Create a pull request
      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          title: "Automated Update"
          body: |
            This pull request was created automatically by the GitHub Action workflow.
